### PR TITLE
Add support of nested fields

### PR DESCRIPTION
**Pull request by mouadino**

### CODE REVIEW

**Comment by fuhrysteve** [comment]
This is great! Thanks!

**Comment by mouadino** [comment]
@fuhrysteve Please let me know in case you need more help to stabilise this library I would love to see it in PyPI soon :)

**Comment by fuhrysteve** [comment]
@mouadino 

If you have any ideas for how to structure it, open a ticket! Either way, I plan to use this for a project that will be delivered by first quarter 2016, so I'd expect no later than then it should be on PyPI.

I want to come up with a more elegant way to implement than pumping a schema into a `dump_schema` method, but I don't want to over-engineer it either.

**Comment by mouadino** [comment]
@fuhrysteve Can you maybe create issues with the use cases that you have in mind, for my side  ``dump_schema`` is exactly what I wanted nothing more (at least for now).

**Comment by fuhrysteve** [comment]
@mouadino Sure thing! So far it accomplishes my needs as well. I do have a couple ideas though.

**Pull request merged**
