### PR TITLE
Supporting recursive nested schemas

### PR DESCRIPTION
**Pull request by stringfellow**
@fuhrysteve this is a bit of a bold rework... I've used the 'definitions' scoping to help and this should now work with e.g. https://github.com/jdorn/json-editor/  (see e.g. [this fiddle](http://jeremydorn.com/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKAKgBQDkVJtRlEAbCbEA40gGnAnQGMAnGAB2TVvokazRAE9uNLCBQAjAFYQ2iEM24cUEjslZkQcAIYBbSeXGSQ6RFzgBzEAF9mbABYxKYDhDi6xE2vo4OfVEVECQIQ0wcEAASTyhaAGIAekhYBD4MZMFSezy85jjoJNToeCRULJyaeyAAA=&value=N4IgdghgtgpiBcIQBoQGMAWBLANgEwCcYwEBtAXQF8gAAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)) but unfortunately brutusin/json-forms doesn't support recursive schemas at the moment.

Note this branch includes #33 and #35 and therefore covers both #32 and #34

### CODE REVIEW

**Comment by stringfellow** [comment]
Hm, think actually this doesn't work with deep nesting. Need to rework to raise all definitions to initial schema dump

**Comment by fuhrysteve** [comment]
This looks great - the only thing I'm worried about is whether this break backwards compatibility with [brutusin/json-forms](https://github.com/brutusin/json-forms)? Obviously it won't support the nesting stuff as you mentioned

**Comment by stringfellow** [comment]
It won't break backwards compat in that it doesn't remove the ability to render the same schemas as it did - brutusin/json-forms supports `$ref`, see e.g. https://jsfiddle.net/ho1p0egb/ - though it will still be broken for recursive schemas, as it was already!

**Comment by stringfellow** [comment]
(also it turns out that other form libs don't handle deep nesting/recursion well.. :( )

**Comment by fuhrysteve** [comment]
Awesome - that gives me some peace of mind because I have some stuff out there that uses brutisin/json-forms that I'd rather not deal with breaking at the moment

I'll merge whenever you're ready - I'll give it a few hrs at least tho in case you have any last minute changes you want to make

Thanks!!! This is great I couldn't even really find anything to nitpick about haha

**Comment by stringfellow** [comment]
Haha... amazing, that is the best news I've had in about a month 🙏🏻
If you don't mind having a look over https://github.com/stringfellow/marshmallow-jsonschema/pull/1 as well (which just adds a little tweak to allow some sugar in simple fields) -- I've opened a PR which contains that here: #37

**Pull request merged**
