### PR TITLE
add field metadata to serialized definition

### LINKED ISSUE #46: Metadata is not serialized (only description and title are)
Using the example from https://github.com/mozilla-services/react-jsonschema-form#multiple-choices-list -- it should be possible to set the `uniqueItems` property of a field. A simple way to allow extra metadata like this is to build on the support in Marshmallow for `kwargs` to be set in the metadata. In a previous issue, the field `kwargs` were added to the metadata (#39) but these were never serialized out. (So effectively useless except for description and title).

### PR DESCRIPTION
**Pull request by stringfellow**
Partially related to #38 and not fixed by #39 -- arbitrary metadata is not added to the serialized output (only description and title are) -- this PR fixes #46, and more generally solves #45

### CODE REVIEW

**Comment by fuhrysteve** [comment]
Thanks for the PR! Can you help me understand why this is using `pop` to retrieve the metadata keys?

**Comment by stringfellow** [comment]
It was to avoid adding the description and title again... but yes... possibly can just omit the specific pop for description and title and let that loop do the job

**Comment by stringfellow** [comment]
Oh and `field.metadata.pop('metadata', {})` is because otherwise you end up with e.g. `{title: "x", description: "y", foo: "bar", metadata: {title: "x", description: "y", foo: "bar"}}`

**Comment by fuhrysteve** [comment]
I'd have to spend some time going through it to recall exactly how this all flows, but my initial fear was that using `.pop()` could somehow trickle down to the original definition of the class since some things are passed by reference. I.e. I'm trying to confirm that if you run this twice on the same attribute that you aren't corrupting the original class definition

**Comment by stringfellow** [comment]
Understood. Will add a test and solve if needed

**Comment by stringfellow** [comment]
@fuhrysteve you're bang on, have fixed (slightly lazily but I think it suffices). Thanks for spotting.

**Pull request merged**
